server:
  port: 8051


logging:
  level:
    root: INFO
    org.springframework:
      web: INFO
      security: INFO
      session: INFO
      data: INFO
      jdbc:
        core:
          JdbcTemplate: INFO
          StatementCreatorUtils: TRACE
    com.cauh: DEBUG
    org.apache.tiles: DEBUG

spring.jndi.ignore: true

spring:
  devtools:
    livereload:
      enabled: true
  main:
    banner-mode: console
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.session.SessionAutoConfiguration
  freemarker:
    settings:
      number_format: 0
#    template-loader-path: classpath:/WEB-INF/templates/
  jackson:
    serialization:
      indent_output: true
  application:
    name: SOP
#  cache:
#    type: redis
#    redis:
#      cache-null-values: false
#      use-key-prefix: false
  jpa:
    open-in-view: true
    properties:
      org:
        hibernate:
          envers:
            audit_table_suffix: _audit
            modified_flag_suffix: _changed
            store_data_at_delete: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 215MB
  profiles:
    active: prod
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  mail:
    host: smtp.office365.com
    port: 587
    protocol: smtp
    username: ISOCAU@caumc.or.kr
    password: ISO14155cau

    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
#http://gw.dtnsm.com/common/download.aspx?DownType=approsign2&sUserID=jhseo&file=jhseo_2019-09-20.png
gw:
  login:
    url: http://gw.dtnsm.com/checker9_new.aspx?txtDomainNum=4&sType=LOGIN&txtUserid={txtUserid}&txtpassword={txtpassword}
  sign-image: http://gw.dtnsm.com/common/download.aspx?DownType=approsign&file=

mail:
  notice:
    name: CAUH System
    address: ISOCAU@caumc.or.kr

#Site별 설정.
site:
  code: "CAUH"
  link: "https://www.caumc.or.kr/"
  company-title: "Chung-Ang University Hospital"
  iso-title: "ISO 14155"
  company-kor-title: "중앙대학교병원"
  footer-msg: "Copyright(c) CHUNG-ANG UNIVERSITY HEALTHCARE SYSTEM, All Rights Reserved."
  image-logo: "https://ch.cauhs.or.kr/images/main_re_logo.gif"
  login-image: "/static/img/login_logo.jpg"

  #세션 타이머(초 단위)
  session-timer: "1800"
  session-minute: "30"
  session-second: "00"

meta:
    description: "Chung-Ang University Healthcare System ISO Management System"
    keywords: "중앙대학교병원,의료기기,임상시험,iso"

sop:
  prefix: "CAUH-"
  deviation-doc-id: "CAUH-QM002"
  agreement-personal-information-doc-id: "CAUH-QM002-RF11"
  disclosure-doc-id: "CAUH-QM002-RF10"

form:
  name: "RF"
  prefix: "-RF"

cert:
  header: "CAUH-ISO 14155 GCP-"

#초 분 시 일 월 요일 연도
scheduler:
  sop-status-update: 0 5 0 * * * #매일 12시 5분 갱신
  training-alert: 0 30 0 * * * #매일 12시 30분 1, 3, 7, 14 일전 교육 알림
#  user-sync: 0 0 8,10,12,14,16,18,20 * * 1-5 #월~금 8시~20시 매 정시
#  agreement-check: 0 25 0 * * * #매일 12시 25분 갱신
  user-refresh: 0 10 0 * * * #매일 12시 10분 갱신
  user-withdrawal: 0 15 0 * * * #매일 12시 15분 갱신

# 시스템 관리자 Role(Job Title) 설정
role:
  admin-1: ADMIN
#  admin-1: QAA
#  admin-2: QAM
#  admin-3: QMO
#  admin-4: QAD
  receive-email: ADMIN

