server:
  port: 8051


logging:
  level:
    root: INFO
    org.springframework:
      web: INFO
      security: INFO
      session: INFO
      data: INFO
      jdbc:
        core:
          JdbcTemplate: INFO
          StatementCreatorUtils: TRACE
    com.dtnsm: DEBUG
    org.apache.tiles: DEBUG

spring.jndi.ignore: true
spring:
  main:
    banner-mode: console
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.session.SessionAutoConfiguration
  freemarker:
    settings:
      number_format: 0
#    template-loader-path: classpath:/WEB-INF/templates/
  jackson:
    serialization:
      indent_output: true
  application:
    name: SOP
#  cache:
#    type: redis
#    redis:
#      cache-null-values: false
#      use-key-prefix: false
  jpa:
    open-in-view: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 215MB
  profiles:
    active: prod
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: safesoft.dev@gmail.com
    password: sa12fe30
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
#http://gw.dtnsm.com/common/download.aspx?DownType=approsign2&sUserID=jhseo&file=jhseo_2019-09-20.png
gw:
  login:
    url: http://gw.dtnsm.com/checker9_new.aspx?txtDomainNum=4&sType=LOGIN&txtUserid={txtUserid}&txtpassword={txtpassword}
  sign-image: http://gw.dtnsm.com/common/download.aspx?DownType=approsign&file=


#초 분 시 일 월 요일 연도
scheduler:
  sop-status-update: 0 5 0 * * *
  training-alert: 0 30 0 * * * #1, 3, 7, 14 일전 교육 알림
  user-sync: 0 0 8,10,12,14,16,18,20 * * 1-5 #월~금 8시~20시 매 정시

# 시스템 관리자 Role(Job Title) 설정
role:
  admin-1: QAA
  admin-2: QAM
  admin-3: QMO
  admin-4: QAD
  receive-email: QAA,QAD

